# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Amber
email:
remote_theme: "mmistakes/so-simple-theme@3.2.0"
domain: embermagma.github.io
description: Not an artist, or much of anything else- just doing things. 
baseurl: "" # the subpath of your site, e.g. /blog
skin: "/assets/css/skins/dark.css"
url: "https://embermagma.github.io"
logo: #path to images
date format: "%B %-d, %Y"
read_time: false
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"
twitter:
  username: "embermagma"  
github:
  username:  "embermagma"
search: true  
liquid:
  error_mode: strict

include:
  - _pages

feed:
  path: atom.xml
sidebar:
        nav: "posts"

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

search_full_content: false

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
layout: collection
plugins: 
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  
collections:
  art:
    output: true
    permalink: /:collection/:path/
  
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
      
- scope:
      path: "_art"
      type: recipes
    values:
      layout: post
      comments: true
      share: true
     
      
entries_layout: grid
collections:
  art:
    output: true
    permalink: /:collection/:path/
    
footer_links:
   - title: Twitter
    url: https://twitter.com/embermagma
    icon: fab fa-twitter-square
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
